### ISSUE TITLE
申请测试版

### ISSUE THREAD

**Issue by Myxer002** [PixelCyber/Thor#96]
求最新版测试1361141860@qq.com已经购买1.35求1.36的

**Comment by mama2000** [comment]
xjdj

**Comment by LikunjieLikunjie** [comment]
求最新版测试oxw4668d@icloud.com已经购买1.35求1.36的

**Comment by lj98lj98** [comment]
同样求1.36测试邀请:  lj98lj98@163.com

**Comment by badmotnon** [comment]
求1.36测试版  z.ruiyang@hotmail.com

**Comment by yinying1341** [comment]
求测试版yinying1341@vip.qq.com

**Comment by pc888999** [comment]
求最新测试版  panchao333@qq.com  

谢谢！

**Comment by dongshiqiang** [comment]
shiqiang0376@hotmail.com

**Comment by yinying1341** [comment]
------------------ 原始邮件 ------------------发件人: dongshiqiang  <notifications@github.com>发送时间: 2019年2月23日 07:55收件人: PixelCyber/Thor <Thor@noreply.github.com>抄送: yinying1341 <yinying1341@163.com>, Comment <comment@noreply.github.com>主题: 回复：[PixelCyber/Thor] 申请测试版 (#96)shiqiang0376@hotmail.com

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PixelCyber/Thor","title":"PixelCyber/Thor","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/PixelCyber/Thor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dongshiqiang in #96: shiqiang0376@hotmail.com"}],"action":{"name":"View Issue","url":"https://github.com/PixelCyber/Thor/issues/96#issuecomment-466588713"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/PixelCyber/Thor/issues/96#issuecomment-466588713",
"url": "https://github.com/PixelCyber/Thor/issues/96#issuecomment-466588713",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
